version: '3.8'
services:
  app:
    image: nvidia/cuda:12.1.0-devel-ubuntu22.04
    runtime: nvidia
    cap_add:
      - SYS_ADMIN
    command: >
      /bin/bash -c "echo 'Starting Container' && echo 'Making Test File' && touch test.txt
      && echo '>>Installing Python Libs' && apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev
      && echo '>>Installing NVIDIA cuDNN' && pip install nvidia-cudnn-cu12==8.9.7.29
      && echo '>>Installing TensorRT-LLM' && pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
      && echo '>>Checking TensorRT-LLM Installation' && python3 -c 'import tensorrt_llm'
      && echo '>>Installing Git and Git-LFS' && apt-get -y install git git-lfs
      && echo '>>Cloning TensorRT-LLM' && git clone https://github.com/NVIDIA/TensorRT-LLM.git
      && echo '>>Installing NSight Systems' && apt-get -y install wget net-tools
      && wget https://developer.nvidia.com/downloads/assets/tools/secure/nsight-systems/2024_2/nsight-systems-2024.2.1_2024.2.1.106-1_amd64.deb
      && apt-get -y install ./nsight-systems-2024.2.1_2024.2.1.106-1_amd64.deb
      && apt --fix-broken -y install
      && echo '*** done, you can detach from logs ***'
      && tail -f /dev/null"
    stdin_open: true
    tty: true
    entrypoint: ''
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /usr/local/nvidia/lib:/usr/local/nvidia/lib
    ports:
      - "8888:8888"
